/* tslint:disable */
/* eslint-disable */
/**
 * Customer API
 * A simple REST API for managing users and organizations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrganizationRequest
 */
export interface CreateOrganizationRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOrganizationRequest
     */
    imageUrls?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CreateOrganizationRequest
     */
    lat: number;
    /**
     * 
     * @type {number}
     * @memberof CreateOrganizationRequest
     */
    lng: number;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateOrganizationRequest interface.
 */
export function instanceOfCreateOrganizationRequest(value: object): value is CreateOrganizationRequest {
    if (!('lat' in value) || value['lat'] === undefined) return false;
    if (!('lng' in value) || value['lng'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateOrganizationRequestFromJSON(json: any): CreateOrganizationRequest {
    return CreateOrganizationRequestFromJSONTyped(json, false);
}

export function CreateOrganizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageUrls': json['image_urls'] == null ? undefined : json['image_urls'],
        'lat': json['lat'],
        'lng': json['lng'],
        'name': json['name'],
    };
}

export function CreateOrganizationRequestToJSON(json: any): CreateOrganizationRequest {
    return CreateOrganizationRequestToJSONTyped(json, false);
}

export function CreateOrganizationRequestToJSONTyped(value?: CreateOrganizationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'description': value['description'],
        'image_urls': value['imageUrls'],
        'lat': value['lat'],
        'lng': value['lng'],
        'name': value['name'],
    };
}

