/* tslint:disable */
/* eslint-disable */
/**
 * Customer API
 * A simple REST API for managing users and organizations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOrganizationsByIDsRequest
 */
export interface GetOrganizationsByIDsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetOrganizationsByIDsRequest
     */
    ids: Array<string>;
}

/**
 * Check if a given object implements the GetOrganizationsByIDsRequest interface.
 */
export function instanceOfGetOrganizationsByIDsRequest(value: object): value is GetOrganizationsByIDsRequest {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    return true;
}

export function GetOrganizationsByIDsRequestFromJSON(json: any): GetOrganizationsByIDsRequest {
    return GetOrganizationsByIDsRequestFromJSONTyped(json, false);
}

export function GetOrganizationsByIDsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrganizationsByIDsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'],
    };
}

export function GetOrganizationsByIDsRequestToJSON(json: any): GetOrganizationsByIDsRequest {
    return GetOrganizationsByIDsRequestToJSONTyped(json, false);
}

export function GetOrganizationsByIDsRequestToJSONTyped(value?: GetOrganizationsByIDsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids': value['ids'],
    };
}

