/* tslint:disable */
/* eslint-disable */
/**
 * Customer API
 * A simple REST API for managing users and organizations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationResponse
 */
export interface OrganizationResponse {
    /**
     * 
     * @type {string}
     * @memberof OrganizationResponse
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationResponse
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationResponse
     */
    id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OrganizationResponse
     */
    imageUrls: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof OrganizationResponse
     */
    lat: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizationResponse
     */
    lng: number;
    /**
     * 
     * @type {string}
     * @memberof OrganizationResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationResponse
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the OrganizationResponse interface.
 */
export function instanceOfOrganizationResponse(value: object): value is OrganizationResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('imageUrls' in value) || value['imageUrls'] === undefined) return false;
    if (!('lat' in value) || value['lat'] === undefined) return false;
    if (!('lng' in value) || value['lng'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function OrganizationResponseFromJSON(json: any): OrganizationResponse {
    return OrganizationResponseFromJSONTyped(json, false);
}

export function OrganizationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'createdAt': json['created_at'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'imageUrls': json['image_urls'],
        'lat': json['lat'],
        'lng': json['lng'],
        'name': json['name'],
        'updatedAt': json['updated_at'],
    };
}

export function OrganizationResponseToJSON(json: any): OrganizationResponse {
    return OrganizationResponseToJSONTyped(json, false);
}

export function OrganizationResponseToJSONTyped(value?: OrganizationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'created_at': value['createdAt'],
        'description': value['description'],
        'id': value['id'],
        'image_urls': value['imageUrls'],
        'lat': value['lat'],
        'lng': value['lng'],
        'name': value['name'],
        'updated_at': value['updatedAt'],
    };
}

