/* tslint:disable */
/* eslint-disable */
/**
 * Customer API
 * A simple REST API for managing users and organizations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberRole } from './MemberRole';
import {
    MemberRoleFromJSON,
    MemberRoleFromJSONTyped,
    MemberRoleToJSON,
    MemberRoleToJSONTyped,
} from './MemberRole';

/**
 * 
 * @export
 * @interface SetRoleRequest
 */
export interface SetRoleRequest {
    /**
     * 
     * @type {MemberRole}
     * @memberof SetRoleRequest
     */
    role: MemberRole;
}



/**
 * Check if a given object implements the SetRoleRequest interface.
 */
export function instanceOfSetRoleRequest(value: object): value is SetRoleRequest {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function SetRoleRequestFromJSON(json: any): SetRoleRequest {
    return SetRoleRequestFromJSONTyped(json, false);
}

export function SetRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'role': MemberRoleFromJSON(json['role']),
    };
}

export function SetRoleRequestToJSON(json: any): SetRoleRequest {
    return SetRoleRequestToJSONTyped(json, false);
}

export function SetRoleRequestToJSONTyped(value?: SetRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': MemberRoleToJSON(value['role']),
    };
}

