/* tslint:disable */
/* eslint-disable */
/**
 * Customer API
 * A simple REST API for managing users and organizations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberRole } from './MemberRole';
import {
    MemberRoleFromJSON,
    MemberRoleFromJSONTyped,
    MemberRoleToJSON,
    MemberRoleToJSONTyped,
} from './MemberRole';

/**
 * 
 * @export
 * @interface UserWithRoleResponse
 */
export interface UserWithRoleResponse {
    /**
     * 
     * @type {string}
     * @memberof UserWithRoleResponse
     */
    avatarUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UserWithRoleResponse
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof UserWithRoleResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UserWithRoleResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserWithRoleResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserWithRoleResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserWithRoleResponse
     */
    phoneNumber?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserWithRoleResponse
     */
    researchCategories: Array<string>;
    /**
     * 
     * @type {MemberRole}
     * @memberof UserWithRoleResponse
     */
    role?: MemberRole;
    /**
     * 
     * @type {string}
     * @memberof UserWithRoleResponse
     */
    socialMedia?: string;
    /**
     * 
     * @type {string}
     * @memberof UserWithRoleResponse
     */
    updatedAt: string;
}



/**
 * Check if a given object implements the UserWithRoleResponse interface.
 */
export function instanceOfUserWithRoleResponse(value: object): value is UserWithRoleResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('researchCategories' in value) || value['researchCategories'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UserWithRoleResponseFromJSON(json: any): UserWithRoleResponse {
    return UserWithRoleResponseFromJSONTyped(json, false);
}

export function UserWithRoleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWithRoleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'createdAt': json['created_at'],
        'description': json['description'] == null ? undefined : json['description'],
        'email': json['email'],
        'id': json['id'],
        'name': json['name'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'researchCategories': json['research_categories'],
        'role': json['role'] == null ? undefined : MemberRoleFromJSON(json['role']),
        'socialMedia': json['social_media'] == null ? undefined : json['social_media'],
        'updatedAt': json['updated_at'],
    };
}

export function UserWithRoleResponseToJSON(json: any): UserWithRoleResponse {
    return UserWithRoleResponseToJSONTyped(json, false);
}

export function UserWithRoleResponseToJSONTyped(value?: UserWithRoleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar_url': value['avatarUrl'],
        'created_at': value['createdAt'],
        'description': value['description'],
        'email': value['email'],
        'id': value['id'],
        'name': value['name'],
        'phone_number': value['phoneNumber'],
        'research_categories': value['researchCategories'],
        'role': MemberRoleToJSON(value['role']),
        'social_media': value['socialMedia'],
        'updated_at': value['updatedAt'],
    };
}

