/* tslint:disable */
/* eslint-disable */
/**
 * Customer API
 * A simple REST API for managing users and organizations
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyCredentialsRequest
 */
export interface VerifyCredentialsRequest {
    /**
     * 
     * @type {string}
     * @memberof VerifyCredentialsRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCredentialsRequest
     */
    password: string;
}

/**
 * Check if a given object implements the VerifyCredentialsRequest interface.
 */
export function instanceOfVerifyCredentialsRequest(value: object): value is VerifyCredentialsRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function VerifyCredentialsRequestFromJSON(json: any): VerifyCredentialsRequest {
    return VerifyCredentialsRequestFromJSONTyped(json, false);
}

export function VerifyCredentialsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyCredentialsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function VerifyCredentialsRequestToJSON(json: any): VerifyCredentialsRequest {
    return VerifyCredentialsRequestToJSONTyped(json, false);
}

export function VerifyCredentialsRequestToJSONTyped(value?: VerifyCredentialsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

