packages:
  - .

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

# temp until this supports eslint v10
patchedDependencies:
  eslint-plugin-react@7.37.5: patches/eslint-plugin-react@7.37.5.patch
