query GetParts {
  parts {
    id
    name
    partNumber
    description
    condition
    isAvailable
    temperatureStage
    images
    manufacturerId
    organizationId
    userId
    manufacturer {
      id
      name
      countryOfOrigin
    }
    categories {
      id
      name
    }
  }
}

query GetPart($id: UUID!) {
  part(id: $id) {
    id
    name
    partNumber
    description
    condition
    isAvailable
    temperatureStage
    images
    manufacturerId
    organizationId
    userId
    manufacturer {
      id
      name
      countryOfOrigin
    }
    categories {
      id
      name
    }
  }
}

query SearchParts($name: String!) {
  searchParts(name: $name) {
    id
    name
    partNumber
    description
    condition
    isAvailable
    temperatureStage
    images
    manufacturerId
    organizationId
    userId
    manufacturer {
      id
      name
      countryOfOrigin
    }
    categories {
      id
      name
    }
  }
}

mutation CreatePart($input: CreatePartInput!) {
  createPart(input: $input) {
    id
    name
    partNumber
  }
}

mutation UpdatePart($id: UUID!, $input: UpdatePartInput!) {
  updatePart(id: $id, input: $input) {
    id
    name
    partNumber
    description
    condition
    isAvailable
    temperatureStage
    images
    manufacturer {
      id
      name
      countryOfOrigin
    }
    categories {
      id
      name
    }
  }
}

mutation DeletePart($id: UUID!) {
  deletePart(id: $id)
}
