query GetProducts {
  products {
    id
    name
    description
    version
    parts {
      id
      partId
      quantity
      notes
      part {
        id
        name
        partNumber
      }
    }
  }
}

query GetProduct($id: UUID!) {
  product(id: $id) {
    id
    name
    description
    version
    models3D
    parts {
      id
      partId
      quantity
      notes
      part {
        id
        name
        partNumber
      }
    }
  }
}

mutation CreateProduct($input: CreateProductInput!) {
  createProduct(input: $input) {
    id
    name
    description
    version
  }
}

mutation AddProductPart($input: AddProductPartInput!) {
  addProductPart(input: $input) {
    id
    productId
    partId
    quantity
    notes
  }
}

mutation RemoveProductPart($id: UUID!) {
  removeProductPart(id: $id)
}

mutation UpdateProduct($id: UUID!, $input: UpdateProductInput!) {
  updateProduct(id: $id, input: $input) {
    id
    name
    description
    version
  }
}

mutation DeleteProduct($id: UUID!) {
  deleteProduct(id: $id)
}

query GetProductInventory {
  productInventory {
    id
    productId
    serialNumber
    isAvailable
    notes
    product {
      id
      name
      version
    }
    partsUsed {
      id
      partId
      serialNumber
      isAvailable
      part {
        id
        name
        partNumber
      }
    }
  }
}

query GetProductInventoryByProduct($productId: UUID!) {
  productInventoryByProduct(productId: $productId) {
    id
    serialNumber
    isAvailable
    notes
    partsUsed {
      id
      partId
      serialNumber
      isAvailable
      part {
        id
        name
        partNumber
      }
    }
  }
}

query GetProductInventoryItem($id: UUID!) {
  productInventoryItem(id: $id) {
    id
    productId
    serialNumber
    isAvailable
    notes
    product {
      id
      name
      version
    }
    partsUsed {
      id
      partId
      serialNumber
      isAvailable
      part {
        id
        name
        partNumber
      }
    }
  }
}

mutation CreateProductInventory($input: CreateProductInventoryInput!) {
  createProductInventory(input: $input) {
    id
    productId
    serialNumber
    isAvailable
    notes
  }
}

mutation UpdateProductInventory(
  $id: UUID!
  $input: UpdateProductInventoryInput!
) {
  updateProductInventory(id: $id, input: $input) {
    id
    productId
    serialNumber
    isAvailable
    notes
  }
}

mutation DeleteProductInventory($id: UUID!) {
  deleteProductInventory(id: $id)
}

mutation AddPartToProductInventory(
  $partsInventoryId: UUID!
  $productInventoryId: UUID!
) {
  addPartToProductInventory(
    partsInventoryId: $partsInventoryId
    productInventoryId: $productInventoryId
  )
}

mutation RemovePartFromProductInventory(
  $partsInventoryId: UUID!
  $productInventoryId: UUID!
) {
  removePartFromProductInventory(
    partsInventoryId: $partsInventoryId
    productInventoryId: $productInventoryId
  )
}
