import "@mantine/core/styles.css";
import "./globals.css";

import type { Metadata } from "next";
import { ReactNode } from "react";

import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Mapfox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
