import "@mantine/core/styles.css";
import "./globals.css";

import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
import type { Metadata } from "next";
import { ReactNode } from "react";

import { Navbar } from "@/components/navbar/Navbar";

import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Mapfox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>
      <body>
        <Providers>
          <Navbar />
          <main style={{ paddingTop: 70 }}>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
